#!/bin/sh

port="${1:-22}"

adresses=$(
  sudo nmap -sS -p $port $(
    ip add |
    grep 'inet 1' |
    awk 'NR>1 { print $2 }'
  ) |
  grep -B 4 open |
  awk '$1 == "Nmap" { print $5 }'
)

echo -e "IPs on local network with port $port open:\n$adresses"
